### ISSUE TITLE
"ModuleNotFoundError: No module named 'constants'" when running linuxmuster-setup

### ISSUE THREAD

**Issue by Yekohama** [linuxmuster/linuxmuster-base7#71]
When trying to run linuxmuster-setup on the `lmn7-server-20190320` vm the following error occurs:
```
Traceback (most recent call last):
  File "/usr/sbin/linuxmuster-setup", line 8, in <module>
    import constants
ModuleNotDoundError: No module named 'constants'
```

**Comment by HappyBasher** [comment]
The system was updated before setup?

**Comment by Yekohama** [comment]
I did update the VM using `apt update && apt dist-upgrade -y`

**Comment by HappyBasher** [comment]
Cannot reproduce this. Perhaps corrupted download of ova file or interrupted dist-upgrade?

**Comment by Yekohama** [comment]
Which downloadlink should I use for ova file?

**Comment by HappyBasher** [comment]
Always these published [here](https://github.com/linuxmuster/linuxmuster-base7/wiki/Die-Appliances).

**Comment by HappyBasher** [comment]
I think thios can be closed.

**Comment by gber** [comment]
I ran into the same issue, this was caused by `pip` which is invoked by the Debian postinstall script installing packages into the home directory of the user who is installing the package instead of root.

This could be avoided by making use of a venv or packaging python dependencies as debian packages.
