### ISSUE TITLE
possible bug in linucmuster-prepair concerning serverkeys

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-base7#81]
Hi there,

could you please have a look at this and decide if there is a BUG?

https://ask.linuxmuster.net/t/linuxmuster-neu-aufsetzen-6-2-oder-7-xcp-oder-kvm/4623/10

Yours
Holger

**Comment by HappyBasher** [comment]
Hi!

I fear i do not really understand what the issue is. The keys created by linuxmuster-prepare are temporary. Final production keys are created during setup.
BTW, please create issues for linuxmuster-prepare in the [related repo](https://github.com/linuxmuster/linuxmuster-prepare).

Regards, Thomas
